// frontend/vue/src/components/QuestionComponent.vue
<template>
  <div>
    <span v-if="isLoading" class="loading loading-spinner text-secondary"></span>
    <div v-else>
      <div v-if="question" class="flex flex-col justify-center items-center">
        <h2 class="text-2xl font-bold mb-4">{{ question.question }}</h2>
        <div class="flex flex-col gap-2">
          <label v-for="option in question.options" :key="option.type" class="flex items-center gap-2">
            <input
              type="radio"
              name="radio-3"
              class="radio radio-secondary"
              :value="option"
              @click="onOptionSelected(option)"
            />
            <span>{{ `${option.type}) ${option.text}` }}</span>
          </label>
        </div>
        <button
          class="btn btn-active btn-primary min-w-60 mt-4 hover:bg-primary-dark"
          :class="{ 'btn-disabled': !selectedAnswer }"
          @click="submitAnswer"
        >
          Bestätigen
        </button>
      </div>
      <div v-else class="flex flex-col justify-center items-center">
        <h2 :class="['text-2xl font-bold mb-4 result', { wrong: isCorrect === false }]">
          {{ isCorrect ? 'Correct!' : 'Incorrect!' }}
        </h2>
        <button
          class="btn btn-active btn-primary min-w-60 mt-4 hover:bg-primary-dark"
          @click="requestRandomQuestions(questionIds)"
        >
          Next Question
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import axios from 'axios';

const question = ref(null);
const selectedAnswer = ref(null);
const isCorrect = ref(null);
const isLoading = ref(true);
const questionIds = ref([]);

const BackendPictures = {
  spring: '@/assets/spring_logo.png',
  django: '@/assets/django_logo.png',
  express: '@/assets/expressjs_logo.png',
};

const fetchQuestionIds = async () => {
  try {
    const response = await axios.get('http://localhost:8080/api/question/ids');
    questionIds.value = response.data;
    requestRandomQuestions(response.data);
  } catch (error) {
    console.error(error);
  }
};

const requestRandomQuestions = async (ids) => {
  isLoading.value = true;
  question.value = null;
  selectedAnswer.value = null;
  isCorrect.value = null;

  try {
    const randomId = ids[Math.floor(Math.random() * ids.length)];
    const response = await axios.get(`http://localhost:8080/api/question/${randomId}`);
    question.value = response.data;
    isLoading.value = false;
  } catch (error) {
    console.error(error);
  }
};

const onOptionSelected = (option) => {
  selectedAnswer.value = option.type;
};

const submitAnswer = async () => {
  if (!selectedAnswer.value || !question.value) return;

  const checkId = question.value.id;
  question.value = null;
  isLoading.value = true;

  try {
    const response = await axios.post('http://localhost:8080/api/question', {
      id: checkId,
      answer: selectedAnswer.value,
    });
    isCorrect.value = response.data.isCorrect;
    isLoading.value = false;
  } catch (error) {
    console.error(error);
  }
};

onMounted(fetchQuestionIds);
</script>

<style scoped>
@import './QuestionComponent.css';
</style>

// frontend/angular/src/app/question/question.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpClient} from "@angular/common/http";
import {AppComponent} from "../app.component";
import {firstValueFrom} from "rxjs";
import {AnswerRes, AnswerType, QuestionHidden} from "api-types";
import {NgClass, NgForOf, NgIf, NgTemplateOutlet} from "@angular/common";
import {QuestionOption} from "api-types/dist/quiz.type";

@Component({
  selector: 'app-question',
  standalone: true,
  imports: [
    NgForOf,
    NgIf,
    NgClass,
    NgTemplateOutlet
  ],
  templateUrl: './question.component.html',
  styleUrl: './question.component.css'
})
export class QuestionComponent implements OnInit{

  private static QUESTIONS: number[] | undefined = undefined;

  protected question: QuestionHidden | undefined = undefined;
  protected selectedAnswer: AnswerType | undefined = undefined;
  protected isCorrect: boolean | undefined = undefined;
  protected isLoading: boolean = true;

  constructor(private http: HttpClient) {
  }

  ngOnInit(): void {
    if (QuestionComponent.QUESTIONS === undefined) {
      firstValueFrom<number[]>(this.http.get<number[]>(AppComponent.API_URL + '/question/ids'))
        .then(r => {
          QuestionComponent.QUESTIONS = r;
          this.requestRandomQuestions();
        })
    } else {
      this.requestRandomQuestions();
    }
  }

  protected requestRandomQuestions(): void {
    this.isLoading = true;
    this.question = undefined;
    this.selectedAnswer = undefined;
    this.isCorrect = undefined;
    firstValueFrom<QuestionHidden>(this.http.get<QuestionHidden>(AppComponent.API_URL + '/question/' + QuestionComponent.QUESTIONS![Math.floor(Math.random() * QuestionComponent.QUESTIONS!.length)]))
      .then(r => {
        this.question = r;
        this.isLoading = false;
        console.log(r);
      });
  }

  protected onOptionSelected(option: QuestionOption): void {
    this.selectedAnswer = option.type;
  }

  protected submitAnswer(): void {
    if(!this.selectedAnswer || !this.question) return;

    const checkId = this.question.id;
    this.question = undefined;
    this.isLoading = true;

    firstValueFrom<AnswerRes>(this.http.post<AnswerRes>(AppComponent.API_URL + '/question', {
      id: checkId,
      answer: this.selectedAnswer
    }))
      .then(r => {
        console.log(r);
        this.isCorrect = r.isCorrect;
        this.isLoading = false;
      });
  }
}

<ng-container *ngIf="isLoading; else content">
  <span class="loading loading-spinner text-secondary"></span>
</ng-container>

<ng-template #content>
  <ng-container *ngIf="question; else result">
    <div class="flex flex-col justify-center items-center">
      <h2 class="text-2xl font-bold mb-4">{{ question.question }}</h2>

      <div class="flex flex-col gap-2">
        <label class="flex items-center gap-2" *ngFor="let option of question.options">
          <input type="radio" name="radio-3" class="radio radio-secondary" [value]="option"
                 (click)="onOptionSelected(option)"/>
          <span>{{ option.type }}) {{ option.text }}</span>
        </label>
      </div>

      <button [ngClass]="{'btn-disabled': !selectedAnswer}"
              class="btn btn-active btn-primary min-w-60 mt-4 hover:bg-primary-dark"
              (click)="submitAnswer()"
      >
        Bestätigen
      </button>
    </div>
  </ng-container>

  <ng-template #result>
    <div class="flex flex-col justify-center items-center">
      <h2 class="text-2xl font-bold mb-4 result"
      [ngClass]="{'wrong': !isCorrect}">
        {{ isCorrect ? 'Correct!' : 'Incorrect!' }}
      </h2>
      <button class="btn btn-active btn-primary min-w-60 mt-4 hover:bg-primary-dark" (click)="requestRandomQuestions()">
        Next Question
      </button>
    </div>
  </ng-template>
</ng-template>
