// frontend/angular/src/app/home/home.component.ts
import { Component } from '@angular/core';
import {Router} from "@angular/router";

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [],
  template: '<button class="btn btn-active btn-primary min-w-60 mt-4" (click)="navigateToQuestion()">Start</button>'
})
export class HomeComponent {

  constructor(private router: Router) {
  }

  protected navigateToQuestion(): void {
    this.router.navigate(['/question']).then(r => {});
  }

}

// frontend/react/example/src/home/HomeComponent.jsx
import React from 'react';
import { useNavigate } from 'react-router-dom';

const HomeComponent = () => {
  const navigate = useNavigate();

  const navigateToQuestion = () => {
    navigate('/question');
  };

  return (
    <button className="btn btn-active btn-primary min-w-60 mt-4" onClick={navigateToQuestion}>
      Start
    </button>
  );
};

export default HomeComponent;
